services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    # esta linea enlaza el codigo con el que estamos trabajando
    volumes:
      - .:/app-webService
    ports:
      - '80:80'